### ISSUE TITLE
Architecture renewal task list

### ISSUE THREAD

**Issue by wwalpha** [wwalpha/pocket-cards-docs#17]
- [x] Create terraform workspace (dev/prod/test)
- [X] Create IAM assume role in prod account
- [ ] Create manual operations for initail
- [ ] Create Infrastructure CI/CD (dev/prod)
  - [ ] Infrastructure automated test ?
- [ ] Create Source CI/CD (dev/prod)
  - [x] Build
  - [ ] Test environment provisioning
  - [ ] Test data import
  - [ ] Test
  - [ ] Deploy
- [ ] Automated Test
  - [ ] Unit test
  - [ ] Combined test
- [ ] Terraform module list
  - [x] settings (only once)
  - [x]  initialize
  - [x] unmutable
  - [x] arhitecture
